version: '3.9'

services:
  web-ui:
    build:
      context: ./services/web-ui
    ports:
      - "${WEB_UI_PORT}:3000"
    env_file:
      - ./.env
    environment:
      PORT: ${WEB_UI_PORT}
      API_URL: ${API_URL}
    restart: always
